# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cosmium < Formula
  desc ""
  homepage "https://github.com/pikami/cosmium"
  version "0.1.7"

  on_macos do
    url "https://github.com/pikami/cosmium/releases/download/v0.1.7/cosmium_0.1.7_darwin_all.tar.gz"
    sha256 "9b0185b19e6cb47e27f508e94b08fc793100bb7b729851888fc3f9e486ea4abb"

    def install
      bin.install "cosmium"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pikami/cosmium/releases/download/v0.1.7/cosmium_0.1.7_linux_amd64.tar.gz"
        sha256 "f4f917b87bb8c7a02c860b64304f29bd8db5121d9962021205203ab522e4c7d6"

        def install
          bin.install "cosmium"
        end
      end
    end
  end
end
