# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cosmium < Formula
  desc ""
  homepage "https://github.com/pikami/cosmium"
  version "0.1.20"

  on_macos do
    url "https://github.com/pikami/cosmium/releases/download/v0.1.20/cosmium_0.1.20_darwin_all.tar.gz"
    sha256 "09562a875e4375e5a98d18d4e22471417940506442a9c0dac6bcf7a7f3847b83"

    def install
      bin.install "cosmium"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pikami/cosmium/releases/download/v0.1.20/cosmium_0.1.20_linux_amd64.tar.gz"
        sha256 "673b7cec8be71ca28a1fadd145e4d8f2ee4854224247d8bdb1129460dff456d2"

        def install
          bin.install "cosmium"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pikami/cosmium/releases/download/v0.1.20/cosmium_0.1.20_linux_arm64.tar.gz"
        sha256 "929e647ee7ee7bcfd011bbd68d5cc5e4f5c20243cf622845a627a4ba966bf879"

        def install
          bin.install "cosmium"
        end
      end
    end
  end
end
